# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MessagesTemplate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessagesTemplate

  pod 'SwiftMessages', '4.1.4'

end

target 'NotificationService' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationService

end
